# Generated by Django 5.1.1 on 2025-06-22 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0008_list_shared_with"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="shared_with",
            field=models.ManyToManyField(
                related_name="shared_lists", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
